bound:
  delta: 0.025
  delta_test: 0.01
dist_init:
  seed: 110
factory:
  bounds:
  - kl
  - mcallister
  data_loader:
    name: cifar10
    params:
      dataset_path: ./data/cifar10
  losses:
  - nll_loss
  - scaled_nll_loss
  - 01_loss
  metrics:
  - accuracy_micro_metric
  - accuracy_macro_metric
  - f1_micro_metric
  - f1_macro_metric
  model:
    name: conv15
    params:
      dataset: cifar10
      in_channels: 3
  posterior_objective:
    name: fquad
    params:
      delta: 0.025
      kl_penalty: 1.0
  prior_objective:
    name: fclassic
    params:
      delta: 0.025
      kl_penalty: 0.0001
log_wandb: true
mcsamples: 1000
pmin: 5.0e-05
posterior:
  training:
    epochs: 1
    lr: 0.001
    momentum: 0.9
    seed: 1135
prior:
  training:
    epochs: 100
    lr: 0.1
    momentum: 0.95
    seed: 1135
sigma: 0.005
split_config:
  batch_size: 250
  dataset_loader_seed: 112
  seed: 111
split_strategy:
  prior_percent: 0.7
  prior_type: learnt
  self_certified: true
  train_percent: 1.0
  val_percent: 0.0
